using System;

namespace TapKnockout.Ability
{
    public static class VerticalSliceAbilityCatalog
    {
        public const int ExpectedAbilityCount = 42;

        public static readonly AbilityCatalogEntry[] Entries =
        {
            new AbilityCatalogEntry("Ability_41_ArcBlast", "skill_arc_blast", "Arc Blast", "Short cone burst in aim direction.", AbilityRarity.Common, AbilityCategory.Attack, AbilityEffectType.EnergyBeam, 1, 22f, 25f, 5f, 0f, 4f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Active, AbilityTag.Area, AbilityTag.Attack), mutuallyExclusiveGroupId: "active_skill_arc_blast"),
            new AbilityCatalogEntry("Ability_42_GroundSlam", "skill_ground_slam", "Ground Slam", "Radial AoE around the player with knockback.", AbilityRarity.Uncommon, AbilityCategory.Attack, AbilityEffectType.EnergyRing, 1, 18f, 25f, 2.5f, 0f, 4f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Active, AbilityTag.Area, AbilityTag.Defensive), mutuallyExclusiveGroupId: "active_skill_ground_slam"),
            new AbilityCatalogEntry("Ability_01_IronCore", "iron_core", "Iron Core", "Increase max health and stabilize the run.", AbilityRarity.Common, AbilityCategory.Defense, AbilityEffectType.MaxHealthUp, 4, 100f, 20f, 0f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Defensive)),
            new AbilityCatalogEntry("Ability_02_PowerChannel", "power_channel", "Power Channel", "Increase attack damage for cleaner wave clears.", AbilityRarity.Common, AbilityCategory.Attack, AbilityEffectType.AttackDamageUp, 5, 100f, 0.15f, 0f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Attack)),
            new AbilityCatalogEntry("Ability_03_BattleRhythm", "battle_rhythm", "Battle Rhythm", "Reduce attack cooldown for a faster primary loop.", AbilityRarity.Common, AbilityCategory.Attack, AbilityEffectType.AttackSpeedUp, 5, 90f, 0.12f, 0f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Attack)),
            new AbilityCatalogEntry("Ability_04_SwiftFootwork", "swift_footwork", "Swift Footwork", "Move faster between danger lanes.", AbilityRarity.Common, AbilityCategory.Utility, AbilityEffectType.MoveSpeedUp, 4, 70f, 0.10f, 0f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Utility)),
            new AbilityCatalogEntry("Ability_05_QuickRelease", "quick_release", "Quick Release", "Projectiles travel faster and feel more responsive.", AbilityRarity.Common, AbilityCategory.Projectile, AbilityEffectType.ProjectileSpeedUp, 4, 65f, 0.18f, 0f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Projectile)),
            new AbilityCatalogEntry("Ability_06_ImpactTraining", "impact_training", "Impact Training", "Dash impact damage increases.", AbilityRarity.Common, AbilityCategory.Dash, AbilityEffectType.DashDamageUp, 5, 95f, 0.20f, 0f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Dash)),
            new AbilityCatalogEntry("Ability_07_ShortFuseDash", "short_fuse_dash", "Short Fuse Dash", "Dash cooldown is reduced.", AbilityRarity.Common, AbilityCategory.Dash, AbilityEffectType.DashCooldownDown, 5, 90f, 0.15f, 0f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Dash)),
            new AbilityCatalogEntry("Ability_08_Bulldozer", "bulldozer", "Bulldozer", "Dash impacts push enemies farther.", AbilityRarity.Uncommon, AbilityCategory.Dash, AbilityEffectType.DashKnockbackUp, 4, 65f, 0.25f, 0f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Dash)),
            new AbilityCatalogEntry("Ability_09_PhaseStep", "phase_step", "Phase Step", "Dash invulnerability window increases slightly.", AbilityRarity.Uncommon, AbilityCategory.Dash, AbilityEffectType.DashIFrameDurationUp, 3, 55f, 0.04f, 0f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Dash, AbilityTag.Defensive)),
            new AbilityCatalogEntry("Ability_10_TwinShot", "twin_shot", "Twin Shot", "Add one extra forward projectile.", AbilityRarity.Rare, AbilityCategory.Projectile, AbilityEffectType.ExtraProjectile, 2, 35f, 1f, 0f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Projectile), mutuallyExclusiveGroupId: "forward_projectile_pattern"),
            new AbilityCatalogEntry("Ability_11_FocusedPair", "focused_pair", "Focused Pair", "Add a tight forward projectile pattern.", AbilityRarity.Uncommon, AbilityCategory.Projectile, AbilityEffectType.FrontProjectile, 2, 45f, 1f, 0f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Projectile), mutuallyExclusiveGroupId: "forward_projectile_pattern"),
            new AbilityCatalogEntry("Ability_12_PiercingBolt", "piercing_bolt", "Piercing Bolt", "Projectiles pierce additional enemies before expiring.", AbilityRarity.Uncommon, AbilityCategory.Projectile, AbilityEffectType.ProjectilePierce, 3, 50f, 1f, 0f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Projectile)),
            new AbilityCatalogEntry("Ability_13_ChainBounce", "chain_bounce", "Chain Bounce", "Projectiles ricochet to nearby enemies after impact.", AbilityRarity.Rare, AbilityCategory.Projectile, AbilityEffectType.ProjectileRicochet, 2, 35f, 1f, 0f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Projectile)),
            new AbilityCatalogEntry("Ability_14_EmberMark", "ember_mark", "Ember Mark", "Projectile hits can burn enemies over time.", AbilityRarity.Uncommon, AbilityCategory.Status, AbilityEffectType.BurnOnHit, 3, 45f, 0.20f, 0f, 3f, 0f, 0.20f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Attack, AbilityTag.ElementFire)),
            new AbilityCatalogEntry("Ability_15_ToxicEdge", "toxic_edge", "Toxic Edge", "Projectile hits can poison enemies over time.", AbilityRarity.Uncommon, AbilityCategory.Status, AbilityEffectType.PoisonOnHit, 3, 45f, 0.20f, 0f, 4f, 0f, 0.20f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Attack, AbilityTag.ElementPoison)),
            new AbilityCatalogEntry("Ability_16_FrostGrip", "frost_grip", "Frost Grip", "Projectile hits can freeze and heavily slow enemies.", AbilityRarity.Rare, AbilityCategory.Status, AbilityEffectType.FreezeOnHit, 3, 35f, 0.15f, 0f, 1.5f, 0f, 0.15f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Attack, AbilityTag.ElementIce)),
            new AbilityCatalogEntry("Ability_17_StormLink", "storm_link", "Storm Link", "Projectile hits can chain lightning to nearby enemies.", AbilityRarity.Rare, AbilityCategory.Status, AbilityEffectType.LightningOnHit, 3, 35f, 0.15f, 0f, 0f, 0f, 0.15f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Attack, AbilityTag.ElementLightning)),
            new AbilityCatalogEntry("Ability_18_ImpactGuard", "impact_guard", "Impact Guard", "Gain a shield charge that blocks the next incoming hit.", AbilityRarity.Uncommon, AbilityCategory.Defense, AbilityEffectType.ShieldPerRoom, 1, 40f, 1f, 0f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Defensive)),
            new AbilityCatalogEntry("Ability_19_SoulRecovery", "soul_recovery", "Soul Recovery", "Heal after killing enemies.", AbilityRarity.Uncommon, AbilityCategory.Defense, AbilityEffectType.HealOnKill, 3, 45f, 5f, 0f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Healing)),
            new AbilityCatalogEntry("Ability_20_BossBreaker", "boss_breaker", "Boss Breaker", "Deal more damage to bosses and mini-bosses.", AbilityRarity.Uncommon, AbilityCategory.Attack, AbilityEffectType.BossDamageUp, 3, 45f, 0.20f, 0f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Attack, AbilityTag.Boss)),
            new AbilityCatalogEntry("Ability_21_LastStand", "last_stand", "Last Stand", "Deal more damage while health is low.", AbilityRarity.Rare, AbilityCategory.Attack, AbilityEffectType.LowHealthDamageUp, 3, 35f, 0.25f, 0.40f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Attack, AbilityTag.RiskReward)),
            new AbilityCatalogEntry("Ability_22_ShockDash", "shock_dash", "Shock Dash", "Dash impacts emit a damaging shockwave.", AbilityRarity.Rare, AbilityCategory.Dash, AbilityEffectType.DashShockwave, 3, 40f, 2.2f, 0.35f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Dash)),
            new AbilityCatalogEntry("Ability_23_StaggerMaster", "stagger_master", "Stagger Master", "Dash impacts stun enemies briefly.", AbilityRarity.Rare, AbilityCategory.Dash, AbilityEffectType.DashStun, 3, 35f, 0.35f, 0f, 0.35f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Dash)),
            new AbilityCatalogEntry("Ability_24_Overrun", "overrun", "Overrun", "Dash kills refund a portion of dash cooldown.", AbilityRarity.Uncommon, AbilityCategory.Dash, AbilityEffectType.DashCooldownRefundOnKill, 3, 40f, 0.20f, 0f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Dash)),
            new AbilityCatalogEntry("Ability_25_WideCharge", "wide_charge", "Wide Charge", "Increase projectile size for more reliable hits.", AbilityRarity.Uncommon, AbilityCategory.Projectile, AbilityEffectType.ProjectileSizeUp, 3, 50f, 0.18f, 0f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Projectile)),
            new AbilityCatalogEntry("Ability_26_GuardedStance", "guarded_stance", "Guarded Stance", "Reduce incoming damage.", AbilityRarity.Common, AbilityCategory.Defense, AbilityEffectType.DamageReductionUp, 4, 70f, 0.08f, 0f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Defensive)),
            new AbilityCatalogEntry("Ability_27_SharpInstinct", "sharp_instinct", "Sharp Instinct", "Increase critical hit chance.", AbilityRarity.Uncommon, AbilityCategory.Attack, AbilityEffectType.CriticalChanceUp, 4, 55f, 0.08f, 0f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Attack)),
            new AbilityCatalogEntry("Ability_28_HeavyCrit", "heavy_crit", "Heavy Crit", "Critical hits deal more damage.", AbilityRarity.Uncommon, AbilityCategory.Attack, AbilityEffectType.CritDamageUp, 3, 45f, 0.30f, 0f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Attack)),
            new AbilityCatalogEntry("Ability_29_TripleFan", "triple_fan", "Triple Fan", "Add diagonal projectiles to each attack.", AbilityRarity.Rare, AbilityCategory.Projectile, AbilityEffectType.DiagonalProjectiles, 2, 35f, 1f, 0f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Projectile), mutuallyExclusiveGroupId: "wide_projectile_pattern"),
            new AbilityCatalogEntry("Ability_30_SideBurst", "side_burst", "Side Burst", "Fire side projectiles for wider coverage.", AbilityRarity.Rare, AbilityCategory.Projectile, AbilityEffectType.SideProjectiles, 2, 35f, 1f, 0f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Projectile), mutuallyExclusiveGroupId: "wide_projectile_pattern"),
            new AbilityCatalogEntry("Ability_31_BackSpark", "back_spark", "Back Spark", "Fire a rear projectile to punish pursuers.", AbilityRarity.Uncommon, AbilityCategory.Projectile, AbilityEffectType.RearProjectile, 2, 40f, 1f, 0f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Projectile)),
            new AbilityCatalogEntry("Ability_32_SeekingSpark", "seeking_spark", "Seeking Spark", "Projectiles steer toward nearby enemies.", AbilityRarity.Rare, AbilityCategory.Projectile, AbilityEffectType.ProjectileHoming, 3, 35f, 0.35f, 0f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Projectile)),
            new AbilityCatalogEntry("Ability_33_WallSkip", "wall_skip", "Wall Skip", "Projectiles can bounce off solid collision once.", AbilityRarity.Uncommon, AbilityCategory.Projectile, AbilityEffectType.ProjectileWallBounce, 2, 35f, 1f, 0f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Projectile)),
            new AbilityCatalogEntry("Ability_34_LongshotFocus", "longshot_focus", "Longshot Focus", "Deal more damage to distant enemies.", AbilityRarity.Uncommon, AbilityCategory.Attack, AbilityEffectType.LongRangeDamageUp, 3, 45f, 0.18f, 6f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Attack, AbilityTag.Projectile)),
            new AbilityCatalogEntry("Ability_35_LightStep", "light_step", "Light Step", "Gain a chance to dodge incoming hits.", AbilityRarity.Rare, AbilityCategory.Defense, AbilityEffectType.DodgeChanceUp, 3, 35f, 0.08f, 0f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Defensive)),
            new AbilityCatalogEntry("Ability_36_PanicWindow", "panic_window", "Panic Window", "Taking damage grants a longer invulnerability window.", AbilityRarity.Rare, AbilityCategory.Defense, AbilityEffectType.InvulnerabilityAfterHit, 2, 35f, 0.8f, 0f, 0.8f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Defensive)),
            new AbilityCatalogEntry("Ability_37_MomentumCore", "momentum_core", "Momentum Core", "Dash impact damage increases while health is low.", AbilityRarity.Rare, AbilityCategory.Dash, AbilityEffectType.DashDamageLowHealth, 3, 35f, 0.35f, 0f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Dash, AbilityTag.RiskReward)),
            new AbilityCatalogEntry("Ability_38_GuardianDash", "guardian_dash", "Guardian Dash", "Your first dash impact each dash grants a shield charge.", AbilityRarity.Rare, AbilityCategory.Dash, AbilityEffectType.DashShieldAfterHit, 1, 30f, 1f, 0f, 0f, 0f, 0f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Dash, AbilityTag.Defensive)),
            new AbilityCatalogEntry("Ability_39_StaticJump", "static_jump", "Static Jump", "Lightning procs become more frequent.", AbilityRarity.Uncommon, AbilityCategory.Status, AbilityEffectType.ChainLightning, 3, 35f, 0.15f, 0f, 0f, 0f, 0.15f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Attack, AbilityTag.ElementLightning)),
            new AbilityCatalogEntry("Ability_40_EmberSurge", "ember_surge", "Ember Surge", "After Ember Mark, burn procs become stronger and more frequent.", AbilityRarity.Epic, AbilityCategory.Status, AbilityEffectType.SuperBurn, 2, 22f, 0.20f, 0f, 3f, 0f, 0.20f, AbilityImplementationStatus.Implemented, Tags(AbilityTag.Attack, AbilityTag.ElementFire, AbilityTag.SuperUpgrade), prerequisiteAbilityIds: Ids("ember_mark"), upgradeGroupId: "fire_status_upgrade")
        };

        private static AbilityTag[] Tags(params AbilityTag[] tags)
        {
            return tags ?? Array.Empty<AbilityTag>();
        }

        private static string[] Ids(params string[] ids)
        {
            return ids ?? Array.Empty<string>();
        }
    }
}
