namespace TapKnockout.VFX
{
    public enum VFXEventType
    {
        DashStart = 0,
        DashTrail = 1,
        DashImpact = 2,
        MeleeHit = 3,
        ProjectileSpawn = 4,
        ProjectileTrail = 5,
        ProjectileHit = 6,
        EnemyHit = 7,
        EnemyDeath = 8,
        EnemyKnockbackDust = 9,
        RoomClear = 10,
        AbilityOffered = 11,
        AbilitySelected = 12,
        BossWarning = 13,
        BossHit = 14,
        BossDeath = 15,
        Pickup = 16,
        Heal = 17,
        GenericBurst = 18,
        WallSlam = 19,
        ChainKnockback = 20,
        PerfectDash = 21,
        ProjectileDodge = 22,
        LowHealthWarning = 23,
        EnemyTelegraph = 24,
        EnemyAttackRelease = 25,
        BossPatternTelegraph = 26,

        AbilityAttackBuff = 30,
        AbilityAttackSpeedBuff = 31,
        AbilityDefenseBuff = 32,
        AbilityMoveSpeedBuff = 33,
        AbilityHealthBuff = 34,
        AbilityDashBuff = 35,
        AbilityDashShockwave = 36,
        AbilityDashPhase = 37,
        AbilityDashStagger = 38,
        AbilityProjectileBuff = 39,
        AbilityProjectileSplit = 40,
        AbilityProjectilePierce = 41,
        AbilityProjectileRicochet = 42,
        AbilityProjectileHoming = 43,
        AbilityProjectileSize = 44,
        AbilityFireProc = 45,
        AbilityPoisonProc = 46,
        AbilityIceProc = 47,
        AbilityLightningProc = 48,
        AbilityShield = 49,
        AbilitySoulHeal = 50,
        AbilityBossBreaker = 51,
        AbilityLowHealthSurge = 52,
        AbilityRewardLuck = 53,
        AbilityPickupFrenzy = 54,
        AbilityOrbital = 55,
        AbilityDrone = 56,
        AbilityBladeStrike = 57,
        AbilityMeteor = 58,
        AbilityEnergyBeam = 59,
        AbilityEnergyRing = 60,
        AbilityRevive = 61,
        AbilityInvulnerability = 62,
        AbilityGenericUpgrade = 63
    }
}
